name: flutter_qr_scanner
description: "A Plugin for reading/scanning QR & Bar codes using Google's Mobile Vision API."
version: 0.0.5
author: Lutfor Rahman <contact.lutforrahman@gmail.com>
homepage: https://github.com/contactlutforrahman

environment:
  sdk: ">=2.0.0 <5.0.0"
  flutter: ">=0.1.7 <3.0.0"

flutter:
  plugin:
    androidPackage: com.github.contactlutforrahman.flutter_qr_scanner
    pluginClass: QrMobileVisionPlugin

dependencies:
  flutter:
    sdk: flutter
  native_device_orientation: ^0.1.0
